### ISSUE TITLE
Crashes 1.18.2 

### ISSUE THREAD

**Issue by KawaiiUzi** [CrimsonDawn45/Fabric-Shield-Lib#80] opened 2022-03-03 18:21 UTC
Crashes with 1.18.2 new update for some reason, Yes on 1.18.2 and this comes up for the crash reason.
.
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:504)

**Comment by CrimsonDawn45** [comment] 2022-03-03 20:12
That's not the full error log, but I think this might be caused by one of the libraries I included in my .jar file in 1.18.2. I was working on Basic Shields and that little bit of error log looks similar to the end of the error log I got.

**Comment by CrimsonDawn45** [comment] 2022-03-03 20:15
I Opened an Issue on Crowdlin Translate's GitHub & I might have to temporarily remove Crowdlin in a minor release.

**Comment by CrimsonDawn45** [comment] 2022-03-04 23:29
This crash should be fixed as of 1.5.3

**Closed by CrimsonDawn45** 2022-03-04 23:29 UTC
Labels: bug
