### ISSUE TITLE
Update FabricShieldLib to work with Fabric's new c:shields common tag

### ISSUE THREAD

**Issue by ricksouth** [CrimsonDawn45/Fabric-Shield-Lib#111] opened 2022-12-11 18:10 UTC
Hi!

I'm looking to add compatibility with shields created via this lib, but would prefer to avoid a hard dependency. When I brought it up in the discord, this PR came out of it: https://github.com/FabricMC/fabric/pull/2727

There's now a c:shields common tag available, which can be accessed via `net/fabricmc/fabric/api/tag/convention/v1/ConventionalItemTags`. I'm not exactly sure how the code is set up, but would it be possible to add that tag to all shields created via the library? With this, people wouldn't have to do it manually, and I can check for that instead of using `instanceof FabricShield`.

For reference, this functionality would be used for [Passive Shield](https://curseforge.com/minecraft/mc-mods/passive-shield-fabric/).

**Comment by CringeStar** [comment] 2022-12-11 18:13
Yeah we were thinking of adding this, and I was about to get to it. I'll close this issue as its kind of a duplicate of #103, I also update the name of that issue. You can expect this feature in the next release of the library, 1.6.2

**Closed by CringeStar** 2022-12-11 18:13 UTC

**Comment by ricksouth** [comment] 2022-12-11 18:52
Good to hear!
