### ISSUE TITLE
1.18.2 weird error message

### ISSUE THREAD

**Issue by ethan629** [CrimsonDawn45/Fabric-Shield-Lib#93] opened 2022-06-17 03:36 UTC
I followed everything and added 
`maven { url = "https://maven.shedaniel.me/" }
maven { url = "https://maven.terraformersmc.com/" }`

but i got the error message 
`java.lang.RuntimeException: Invalid module: private static transient int[] me.shedaniel.autoconfig.example.ExampleConfig.__$lineHits$__
`

any help?

**Comment by CrimsonDawn45** [comment] 2022-09-05 19:08
Duplicate of #83

**Closed by CrimsonDawn45** 2022-09-05 19:08 UTC
Labels: duplicate
